### PR TITLE
Ssl labs client support

### PR DESCRIPTION
**Pull request by jvehent**
This new worker and surrounding changes implement #129 : a method to determine client support using SSLLabs publicly provided data. The analysis worker uses cipherscan output and compares each server ciphersuite with the ciphersuites supported by the client. If a match is found (using ciphersuites code points), the client is marked as supported and the matching ciphersuite is recorded.

r? @0xdiba and @marumari

### CODE REVIEW

**Comment by jvehent** [comment]
I added a few commits to make this better.

First of all, we don't use generated code anymore. Instead, a new constants package has an almost exhaustive list of TLS parameters that any other package can use. It might also be fun to export those constants in API endpoints, so other people can rely on them.

Second, the client support analyser now check for PFS and protocol support, and stores that information in the output.

This is starting to look good. Here's an example output: https://gist.github.com/jvehent/e870eb135424205a658b21f5e71dfaf6

**Comment by jvehent** [comment]
@marumari : I'm particularly interested in your take on the JSON schema of the analysis output, and if we should break up the product name (Firefox, Chrome, Safari) and its version (27, 28, 29) to make it easier to detect the oldest supported version for a given browser.

**Comment by jvehent** [comment]
@marumari: do you have any opinion on the output format, or is this one to your liking?
https://gist.github.com/jvehent/e870eb135424205a658b21f5e71dfaf6

**Comment by marumari** [comment]
Err, I swear I responded.  WTF...

**Comment by marumari** [comment]
```
    "IE 8-10": {
      "is_supported": false
}
```

This is a bit awkward, I'd rather simply check them each and create the string myself.  This would probably be a lot easier if the format was, instead of this:

```json
    "Chrome 39": {
      "code": 49195,
      "curve": "secp256r1",
      "protocol": "TLSv1.2",
      "ciphersuite": "ECDHE-ECDSA-AES128-GCM-SHA256",
      "is_supported": true
    },
    "Chrome 40": {
      "code": 49195,
      "curve": "secp256r1",
      "protocol": "TLSv1.2",
      "ciphersuite": "ECDHE-ECDSA-AES128-GCM-SHA256",
      "is_supported": true
}
```

Something like this:

```json
Chrome: {
  "39": {
    "code": 49195,
    "curve": "secp256r1",
    "protocol": "TLSv1.2",
    "ciphersuite": "ECDHE-ECDSA-AES128-GCM-SHA256",
    "is_supported": true
  },
  "40": {
    "code": 49195,
    "curve": "secp256r1",
    "protocol": "TLSv1.2",
    "ciphersuite": "ECDHE-ECDSA-AES128-GCM-SHA256",
    "is_supported": true
  }
}
```

You could also do it like this:
Chrome: `[[39, {...}], [40, {...}]]`

They both have their advantages and disadvantages: the latter makes it easier to find the most recent version, the prior makes it easier to query a single version without iterating the list.

Also, instead of this:

```
  "curve": "secp256r1",
  "protocol": "TLSv1.2",
  "ciphersuite": "ECDHE-ECDSA-AES128-GCM-SHA256"
```

You may want to have code points instead, so you're not constantly repeating long strings.  Up to you.  :)

**Comment by jvehent** [comment]
I added the curve and protocol codes (ciphersuite was already added).

Version will always have to be a string, not a float, because each product handles it differently. That makes finding the oldest version a little tricky. We'll need special code to handle that 😞 

The next best thing is to go with a format like the following:
```json
    {
      "id": 149,
      "analyzer": "sslLabsClientSupport",
      "result": [
        {
          "name": "Android",
          "curve": "secp256r1",
          "version": "4.4.2",
          "protocol": "TLSv1.2",
          "curve_code": 23,
          "ciphersuite": "ECDHE-ECDSA-AES256-GCM-SHA384",
          "is_supported": true,
          "protocol_code": 771,
          "ciphersuite_code": 49196
        },
        {
          "name": "Android",
          "curve": "secp256r1",
          "version": "5.0.0",
          "protocol": "TLSv1.2",
          "curve_code": 23,
          "ciphersuite": "ECDHE-ECDSA-AES128-GCM-SHA256",
          "is_supported": true,
          "protocol_code": 771,
          "ciphersuite_code": 49195
        }
      ]
    }
```

**Pull request merged**
