### PR TITLE
Minor cleanups (and XSS fix)

### PR DESCRIPTION
**Pull request by KellerFuchs**
- [x] Removes some minor repetition.
- [x] Fixes minor HTML syntax issues.
- [x] Replaces HTML constructed with raw strings with DOM manipulation.
      This fixes a few XSS issues (that were mitigated by the CSP anyway); it also ought to be faster (`innerHTML` causes the text to be reparsed), but that doesn't really matter here.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
Do not merge yet, it's not properly tested.
(There is lovely doc on how to spinup a test instance, but it's half past midnight and I'm full of sushi)

**Comment by jvehent** [comment]
> Do not merge yet, it's not properly tested.
Is this still the case?

@gguthe: could you take a quick look and share your comments? This is passed my js fuu.

**Comment by KellerFuchs** [comment]
On Wed, Jan 18, 2017 at 12:25:00PM -0800, Julien Vehent [:ulfr] wrote:
> > Do not merge yet, it's not properly tested.
> Is this still the case?

Yes.  I'm down with CCCbola and it got worse  :V


> @gguthe: could you take a quick look and share your comments? This is passed my js fuu.

OK, I'm surprised since my JS-fu is mostly non-existent.
(I used MDN and the devtools a lot to figure it out, though  :>)

**Comment by g-k** [comment]
👍 💯  lgtm

I thought we got the assignments to innerHTML earlier.

**Comment by g-k** [comment]
Applied the following patch:

```diff
diff --git a/static/certsplainer.js b/static/certsplainer.js
index 7f1ba97..4678697 100644
--- a/static/certsplainer.js
+++ b/static/certsplainer.js
@@ -93,6 +93,7 @@ function setField(field, value) {
     let node = document.getElementById(field);

     switch (typeof value) {
+    case 'number':
     case 'string':
        // Setting textContent removes all child nodes
        node.textContent = value;
@@ -100,7 +101,7 @@ function setField(field, value) {

     case 'object':
        let newNode = node.cloneNode(false);
-       newNode.addChild(value);
+       newNode.appendChild(value);
        node.parentNode.replaceChild(newNode, node);
        break;

```

and functional tested:

- [x] load the page  
- [x] decode https://ulfr.io/f/AmazonRootCA1.cer
- [x] links work
- [x] cert path graph displayed

**Comment by KellerFuchs** [comment]
Let's finish with @g-k's PR.

**Pull request closed without merging**
