### PR TITLE
Reorganize repository structure

### PR DESCRIPTION
**Pull request by jvehent**
I changed a bunch of directories around, to make the repository more go-ish. I also changed some of the goroutine logic in the tlsobs-scanner (formely tlsObserver) to be more linear.
Both tlsobs-scanner and tlsobs-api build with go get, but I have not tested deployment or functionality.

@0xDiBa: r?

### CODE REVIEW

**Comment by 0xDiBa** [comment]
Looks good. :+1: 
I like your naming better than mine.
tlsobs-scanner is going to change more once the additional workers come in...

**Comment by jvehent** [comment]
When you mean `change`, do you mean the code or the naming?
The code has to change for sure, since I removed the rabbitmq support and just put a dumb channel in there that doesn't do anything. We'll have to replace that with the SELECT FOR UPDATE logic that feeds new scan IDs into the incomingScans channel.

**Comment by 0xDiBa** [comment]
The code of course ;)

**Comment by 0xDiBa** [comment]
Since it has not been merged yet, I made a patch here.
Messaging through postgres now works.

**Comment by jvehent** [comment]
awesome! thanks!

**Pull request merged**
