### PR TITLE
connection: Print stderr from running cipherscan

### PR DESCRIPTION
**Pull request by adamdecaf**
I had an old version of bash, but didn't find out until running `cipherscan` manually.

### CODE REVIEW

**Comment by tomato42** [comment]
I wonder if it shouldn't be detected through return codes

**Comment by adamdecaf** [comment]
Perhaps, but I was just getting `exit status 1`.

**Comment by jvehent** [comment]
Perhaps only log if cipherscan returns a non-zero error code? That would reduce verbosity.

**Comment by tomato42** [comment]
> Perhaps, but I was just getting `exit status 1`.

honestly I don't recall cipherscan code now, but if that `1` is not unique, maybe we should have a unique code that means "sanity of environment not established, either bash or openssl missing"

printing full cipherscan output on any error code would also work nicely

**Comment by adamdecaf** [comment]
> printing full cipherscan output on any error code would also work nicely

I can print stdout too in this PR. 

I don't think `exit status 1` gives us anything, but we can keep printing errors on any failure.

**Pull request merged**
