### PR TITLE
Use stdlib context

### PR DESCRIPTION
**Pull request by 0xdiba**
The addition of context to the stdlib causes problems with the context provided by gorilla framework.
#139 is caused by this. 
To merge this, the project will have to be Go1.7+ only. If we want to remain compatible with past version of go we can investigate other solutions.

@jvehent ?

### CODE REVIEW

**Comment by jvehent** [comment]
I'm in favor. Maybe add a note to the README?

**Comment by 0xdiba** [comment]
Definitely.
Would it make sense to tag the most recent backwards compatible version?
Not that it would make much difference since upgrading is, in most cases,
trivial.

**Comment by jvehent** [comment]
Nah. No need to maintain compatibility. People should use 1.7.

**Comment by 0xdiba** [comment]
@jvehent Merging?

**Pull request merged**
