### PR TITLE
issuer and subject are now jsonb fields

### PR DESCRIPTION
**Pull request by 0xDiBa**
The proposed change breaks the current database schema as the issuer and subject fields are going from varchar to jsonb.

I think dropping and recreating these columns is the best thing we can do. 
Should I create a script to go through the whole certificates table, parse certificates and save the new form of the issuer and subject fields?

### CODE REVIEW

**Comment by jvehent** [comment]
We can drop and recreate, but you should write a script that reparse existing certificates using the raw_cert to repopulate the columns.

If possible, we should only do one pass over the certificates table and add the `domains` column as well. Can you add a commit for that?

**Comment by 0xDiBa** [comment]
Yeah i had that in mind too.
They are in the same issue.
The domains column should include the sucject common name and the subject
alternative names right?

**Comment by jvehent** [comment]
> The domains column should include the sucject common name and the subject alternative names right?
Yes, as a string, comma separated

**Comment by 0xDiBa** [comment]
Below commands are probably going to be needed for the database: 
```ALTER TABLE certificates DROP COLUMN subject;
ALTER TABLE certificates DROP COLUMN issuer;
ALTER TABLE certificates ADD COLUMN subject jsonb;                                                                                                                                                
ALTER TABLE certificates ADD COLUMN issuer jsonb;
ALTER TABLE certificates ADD COLUMN domains varchar;```

I also changed the offset logic from the fixvalidity.go script a little bit because I could not parse
all the certificates in on pass.

**Comment by jvehent** [comment]
It's working. I think the API needs to be updated to serve the new `domains` column?

**Comment by 0xDiBa** [comment]
I intentionally did not include it.
It's definitely info that is useful inside the database but on the other
side
Do we want to transfer duplicate info again over the net?
If it is needed it can easily be added to the certificate struct and be
served through the api.

**Comment by jvehent** [comment]
That's reasonable, we can omit it from the API and let people look into subject and subjectAlternateName.

So, this looks good, I'm merging it :+1:

**Comment by jvehent** [comment]
quick update: it tooks ~30 hours, but the production DB is now entirely converted to the new format! :beers:

**Comment by 0xDiBa** [comment]
That took a lot...
We should have done the parsing and storage in separate goroutines for each cert.
I did not know we had that many certs indexed already ;)

**Pull request merged**
